DROP TABLE
    CASE10_UNI_1_ONE CASCADE constraints purge;
CREATE TABLE
    CASE10_UNI_1_ONE
    (     
        CASE10_UNI_1_ONE_ID VARCHAR2(20) NOT NULL,
        CASE10_UNI_1_ONE_NAME VARCHAR2(20),
        PRIMARY KEY (CASE10_UNI_1_ONE_ID)
    );

DROP TABLE
    CASE10_UNI_1_MANY CASCADE constraints purge;
CREATE TABLE
    CASE10_UNI_1_MANY
    (
        CASE10_UNI_1_MANY_ID VARCHAR2(20) NOT NULL,
        CASE10_UNI_1_MANY_NAME VARCHAR2(20),
        CASE10_UNI_1_ONE_ID VARCHAR2(20),
        PRIMARY KEY (CASE10_UNI_1_MANY_ID)
    );
