DROP TABLE
    CASE8_BI_1_MANY_1 CASCADE constraints purge;
CREATE TABLE
    CASE8_BI_1_MANY_1
    (     
        CASE8_BI_1_MANY_1_ID VARCHAR2(20) NOT NULL,
        CASE8_BI_1_MANY_1_NAME VARCHAR2(20),
        PRIMARY KEY (CASE8_BI_1_MANY_1_ID)
    );
    
DROP TABLE
    CASE8_BI_1_MANY_2 CASCADE constraints purge;
CREATE TABLE
    CASE8_BI_1_MANY_2
    (     
        CASE8_BI_1_MANY_2_ID VARCHAR2(20) NOT NULL,
        CASE8_BI_1_MANY_2_NAME VARCHAR2(20),
        PRIMARY KEY (CASE8_BI_1_MANY_2_ID)
    );
    

DROP TABLE
    CASE8_BI_1_MANY_1_MANY_2 CASCADE constraints purge;
CREATE TABLE
    CASE8_BI_1_MANY_1_MANY_2
    (     
        CASE8_BI_1_MANY_1_ID VARCHAR2(20) NOT NULL,
        CASE8_BI_1_MANY_2_ID VARCHAR2(20) NOT NULL
    );
