DROP TABLE
    CASE7_UNI_1_ONE CASCADE constraints purge;
CREATE TABLE
    CASE7_UNI_1_ONE
    (     
        CASE7_UNI_1_ONE_ID VARCHAR2(20) NOT NULL,
        CASE7_UNI_1_ONE_NAME VARCHAR2(20),
        PRIMARY KEY (CASE7_UNI_1_ONE_ID)
    );

DROP TABLE
    CASE7_UNI_1_MANY CASCADE constraints purge;
CREATE TABLE
    CASE7_UNI_1_MANY
    (
        CASE7_UNI_1_MANY_ID VARCHAR2(20) NOT NULL,
        CASE7_UNI_1_MANY_NAME VARCHAR2(20),
        CASE7_UNI_1_ONE_ID VARCHAR2(20),
        PRIMARY KEY (CASE7_UNI_1_MANY_ID)
    );
